### ISSUE TITLE
Is the solution available?

### ISSUE THREAD

**Issue by Rouzip** [rflamary/OTML_Statlearn2018#2]
Thanks a lot for your contribution in this project. I learn a lot from the practice. I have tried my own answer for many times, but got 404. So I want to ask whether the solution still available?

**Comment by rflamary** [comment]
Yes it is, I should probably be more precise since people seem to have a hard time finding it.

Note that in order to get NUMBER you need to:

1. Use the cost matrix with cityblock distance (without normalization)
2. Solve the OT problem with the masses given (again no normalization as sum to one)
3. Compute the OT loss

**Comment by Rouzip** [comment]
Thanks for your response, I will try again to find right answer.
